//Styles
import "~/styles/globals.css"
import "~/styles/react-flow-styles.css"

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return <div className="bg-primary-100">{children}</div>
}
